#[firefly]
#x.x.x.x

#[firefly:vars]
#ansible_python_interpreter=/usr/bin/python3
#ansible_ssh_user=ubuntu
#ansible_ssh_private_key_file=~/.ssh/firefly

[re-sacha]
127.0.0.1

[re-sacha:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_user=sacha
ansible_ssh_private_key_file=~/.ssh/re-sacha
