#[firefly]
#x.x.x.x

#[firefly:vars]
#ansible_python_interpreter=/usr/bin/python3
#ansible_ssh_user=ubuntu
#ansible_ssh_private_key_file=~/.ssh/firefly

[pi01]
192.168.0.248

[pi01:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/pi01
